module.exports.links = [
  ['CSDN', 'https://blog.csdn.net/AABBbaby/article/details/130193656', '6'],
  ['少数派', 'https://sspai.com/post/76060', '21'],
  ['wikipedia', 'https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD', '60'],
  ['wikipedia', 'https://en.wikipedia.org/wiki/China', '58'],
  ['51cto', 'https://blog.51cto.com/harmonyos/5318953', '13'],
  ['微信', 'https://mp.weixin.qq.com/s/au2vtN4b_xSVZ1x_ADNO8w', '13'],
  ['微信', 'https://mp.weixin.qq.com/s/hERgwl3TKM2DzDqAe5Fi-A', '17'],
  ['微信', 'https://mp.weixin.qq.com/s/7hMdPkNcFihKXypKY2DMHg', '21'],
  ['掘金', 'https://juejin.cn/post/7135756687134162980', '5'],
  ['知乎', 'https://zhuanlan.zhihu.com/p/24650288', '62'],
  ['开源中国', 'https://my.oschina.net/u/4843764/blog/5528481', '18'],
  ['博客园', 'https://www.cnblogs.com/teach/p/16295605.html', '11'],
  ['CSDN', 'https://blog.csdn.net/csdnnews/article/details/124880259', '2'],
  ['思否', 'https://segmentfault.com/a/1190000041806654', '5'],
  ['MDN', 'https://developer.mozilla.org/zh-CN/docs/Web/API/Window/location', '15'],
  ['简书', 'https://www.jianshu.com/p/a2cb1e3a79be', '17'],
  ['iteye', 'https://www.iteye.com/blog/kaizi1992-2538691', '5'],
  ['iteye', 'https://www.iteye.com/news/32983', '29'],
  ['VS Code Doc', 'https://code.visualstudio.com/docs/terminal/profiles', '11'],
  ['React Doc(EN)', 'https://react.dev/learn/tutorial-tic-tac-toe', '21'],
  ['React Doc(legacy)', 'https://legacy.reactjs.org/docs/getting-started.html', '19'],
  ['React Native', 'https://reactnative.dev/docs/getting-started', '6'],
  ['Create React App', 'https://create-react-app.dev/docs/getting-started/', '13'],
  ['Vue3', 'https://vuejs.org/guide/typescript/overview.html', '11'],
  ['Angular', 'https://angular.io/start/start-data', '14'],
  ['svelte', 'https://svelte.dev/docs', '129'],
  ['Preact', 'https://preactjs.com/guide/v10/getting-started/', '15'],
  ['Vite', 'https://vitejs.dev/config/server-options.html', '17'],
  ['Webpack', 'https://webpack.js.org/concepts/module-federation/', '21'],
  ['Puppeteer', 'https://pptr.dev/guides/debugging', '10'],
  ['tsconfig', 'https://www.typescriptlang.org/tsconfig', '159'],
  ['Github(EN)', 'https://github.com/facebook/react', '9'],
  ['Github', 'https://github.com/Whilconn/one-toc/issues/7', '4'],
  ['Eslint(EN)', 'https://eslint.org/docs/user-guide/getting-started', '6'],
  ['Echarts', 'https://echarts.apache.org/handbook/zh/concepts/dataset/', '13'],
  ['docusaurus', 'https://docusaurus.io/docs', '15'],
  ['NCBI(EN)', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6742634/', '11'],
  // TODO: 内容在 iframe 中；开启content_scripts.all_frames，识别内容区唯一iframe
  // ['threejs', 'https://threejs.org/docs/index.html#manual/en/introduction/Installation', '15'],
];
